In [1]:
import numpy as np
a = np.array([[1, 2, 4], [3, 5, 4], [3, 2, 5]])
b = np.array([3, 4, 3])
print(np.linalg.solve(a, b))

[-0.28  0.52  0.56]


In [2]:
teks = 'abid Juliant Indraswara AIUEO'
vokal = 'aiueoAIUEO'
lib = {'a' : '1', 'i' : '2', 'u' : '3', 'e' : '4', 'o' : '5'}
for i in range(0, len(teks)):
  if teks[i] in vokal:
    huruf = teks[i].lower()
    teks = teks.replace(teks[i], huruf)
    teks = teks.replace(huruf, lib[huruf])

print(teks)

1b2d J3l21nt 2ndr1sw1r1 12345


In [3]:
for i in range(1, 10, 3):
  print(i)

1
4
7


In [4]:
angka = []
for i in range(9, 1, -2):
  angka.append(i)
print(angka)

[9, 7, 5, 3]


In [5]:
def deret(awal, akhir, sel):
  if awal > akhir:
    sel /= -1
  for i in range(awal, akhir, int(sel)):
    print(i)

deret(10, 5, 1)

10
9
8
7
6


In [6]:
for i in range(12, 1, -1):
  if i % 2 != 0:
    print(i)

11
9
7
5
3


In [8]:
teks = 'Abid Juliant Indraswara AIUEO'
vokal = "aiueoAIUEO"
lib = {'a' : '1', 'i' : '2', 'u' : '3', 'e' : '4', 'o' : '5'}

for i in range(0, len(teks)):
  if teks[i] in vokal:
    huruf = teks[i].lower()
    teks = teks.replace(teks[i], huruf)
    teks = teks.replace(huruf, lib[huruf])
  

print(teks)


1b2d J3l21nt 2ndr1sw1r1 12345


In [9]:
import numpy as np
a = np.array([[1, 2, 4], [4, 5, 3], [7, 4, 6]])
b = np.array([3, 2, 6])
txt = np.linalg.solve(a, b)
print(txt)

[ 0.34375  -0.390625  0.859375]


In [10]:
txt = 'Fauzan Tri Nugroho'
print(txt[9:6:-1])
print(txt[-13::-1])

irT
nazuaF


In [11]:
angka = []
def deret(input):
  for i in range(input, 1, -1):
    if i % 2 != 0:
      angka.append(i)
  print(angka)

deret(10)

[9, 7, 5, 3]


In [12]:
20 % 2

0

In [13]:
teks = 'Abid Juliant Indraswara AIUEO'
vokal = 'aiueoAIUEO'
lib = {'a' : '1', 'i' : '2', 'u' : '3', 'e' : '4', 'o' : '5'}

for i in range(0, len(teks)):
  if teks[i] in vokal:
    huruf = teks[i].lower()
    teks = teks.replace(teks[i], huruf)
    teks = teks.replace(huruf, lib[huruf])

print(teks)

1b2d J3l21nt 2ndr1sw1r1 12345


In [14]:
angka = []
def deret(input):
  for i in range(input, 1, -1):
    if i % 2 != 0:
      angka.append(i)
  print(angka)

deret(10)

[9, 7, 5, 3]


In [15]:
teks = 'Aku anak Indonesias'
jml = len(teks)
if jml % 2 == 0:
  print('even')
else:
  print('odd')

odd


In [16]:
import numpy as np
a = np.array([[1,3,6], [5,4,7], [4,3,7]])
b = np.array([3,5,8])
print(np.linalg.solve(a,b))

[ 0.9 -3.9  2.3]


In [17]:
# Fungsi Reverse
def reverse(s): 
    str = "" 
    for i in s: 
        str = i + str 
    return str 

s = "Hello World" 
print ("String awal : ",end="") 
print (s) 

print ("String yang sudah dibalik : ",end="") 
print (reverse(s)) 

String awal : Hello World
String yang sudah dibalik : dlroW olleH
